### ISSUE TITLE
Username and password

### ISSUE THREAD

**Issue by MagnusErler** [timothyle97/Invoxia-HA#2]
When Installing the integration in HA it asks for a username and password. I assume it is my Invoxia email and password. When provided this, HA comes with the following error:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/invoxia/__init__.py", line 38, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'`

**Comment by MagnusErler** [comment]
I fixed this by adding in line 38:

`hass.async_create_task(
        hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    )`
