### ISSUE TITLE
Broken as in Home Assistant 2025.11 (async_config_entry_first_refresh in state ConfigEntryState.LOADED)

### ISSUE THREAD

**Issue by Soicnarf** [timothyle97/Invoxia-HA#5]
Hello,

first thank you very much for this integration and your great work !

It seems that the integration is broken due to Home Assistant 2025.11:
RuntimeError: Detected code that uses `async_config_entry_first_refresh`, which is only supported when entry state is ConfigEntryState.SETUP_IN_PROGRESS, but it is in state ConfigEntryState.LOADED, This will stop working in Home Assistant 2025.11

Thanks !
François

Here is the full detail log:
2024-11-07 09:39:26.334 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up invoxia platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 148, in report
    integration_frame = get_integration_frame(
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 108, in get_integration_frame
    raise MissingIntegrationFrame
homeassistant.helpers.frame.MissingIntegrationFrame

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/invoxia/device_tracker.py", line 37, in async_setup_entry
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in async_config_entry_first_refresh
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 154, in report
    raise RuntimeError(msg) from err
RuntimeError: Detected code that uses `async_config_entry_first_refresh`, which is only supported when entry state is ConfigEntryState.SETUP_IN_PROGRESS, but it is in state ConfigEntryState.LOADED, This will stop working in Home Assistant 2025.11. Please report this issue.
2024-11-07 09:39:26.336 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setups for integration invoxia with title: xxxx@xxx.com and entry_id: xxxxxxxx, during setup without awaiting async_forward_entry_setups, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2254, in async_forward_entry_setups
    _report_non_awaited_platform_forwards(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1194, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 156, in report
    _LOGGER.warning(msg, stack_info=True)

**Comment by calielc** [comment]
Same happend with me since the upgrade to 2024.11.

I tried to remove the integration and readd again, now it does not identity any tracker.
